# The URL the site will be built for
base_url = "https://zom.wtf"
title = "zom.wtf"
theme = "apollo"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
minify_html = true
generate_feed = true
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
toc = true
use_cdn = false
favicon = "/corro.svg"

# Put all your custom variables here
socials = [
    { name = "twitter", url = "https://twitter.com/zommiommy", icon = "twitter" },
    { name = "github", url = "https://github.com/zommiommy", icon = "github" },
#    { name = "scholar", url = "https://scholar.google.com/citations?hl=en&user=9oTPcNUAAAAJ", icon = "scholar" },
#    { name = "orcid", url = "https://orcid.org/0000-0002-9806-3493", icon = "orcid" },
]

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
#    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
    { name = "/good_stuff", url = "/goodstuff", weight = 4 },
]

stylesheets = [
    "override.css",
]
